
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace datamodel
{

using System;
    using System.Collections.Generic;
    
public partial class AccountLogin
{

    public int Id { get; set; }

    public Nullable<int> Account_Id { get; set; }

    public Nullable<System.DateTime> DateLogin { get; set; }

    public Nullable<System.DateTime> DateLogout { get; set; }

}

}
